services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build:
        context: .
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install apache-airflow-providers-docker &&
              airflow db migrate &&
               airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock 

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: b8fdd343af2a69d1b0501072963e253f

  airflow-scheduler:
    build:
        context: .
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - airflow-webserver
    command: >
      bash -c "airflow db migrate && airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: b8fdd343af2a69d1b0501072963e253f

volumes:
  postgres-db-volume:

networks:
  default:
    external: true
    name: animeverse-net
